export const images = {
  background: require('../assets/images/background.png'),
  logo: require('../assets/images/logo.png'),
  card: require('../assets/images/card.png'),
  lock: require('../assets/images/lock.png'),
  leftarrow: require('../assets/images/leftarrow.png'),
  news: require('../assets/images/news.png'),
  tools: require('../assets/images/tools.png'),
  dealer: require('../assets/images/dealer.png'),
  folder: require('../assets/images/folder.png'),
  policy: require('../assets/images/policy.png'),
  profile: require('../assets/images/profile.png'),
  bell: require('../assets/images/bell.png'),
  img1: require('../assets/images/img1.png'),
  img2: require('../assets/images/img2.png'),
  img3: require('../assets/images/img3.png'),
  img4: require('../assets/images/img4.png'),
  img5: require('../assets/images/img5.png'),
};
