export const strings = {
  rut: 'RUT',
  password: 'Contraseña',
  login: 'Iniciar sesión',
  signup: 'Regístrate aquí',
  forgotPassword: 'Olvide mi contraseña',
  noAccount: '¿No tienes una cuenta?',
  recoverPass: 'RECUPERAR CONTRASEÑA',
  enterRut: 'Ingresa tu RUT',
  following: 'Siguiente',
  codeValidate: 'VALIDACIÓN DE CÓDIGO',
  code: 'Código',
  enterCode: 'Ingresa el código enviado a tu correo',
  changePass: 'CAMBIAR CONTRASEÑA',
  enterPass: 'Ingresa una contraseña',
  retypePass: 'Repetir contraseña',
  enterNewPass: 'Ingresa nueva contraseña',
  newPass: 'Nueva contraseña',
  writePassAgain: 'Vuelve a escribir la contraseña',
  codeSent: 'CÓDIGO ENVIADO',
  temporaryCode: 'Hemos enviado un código provisorio a tu correo electrónico.',
  existingRegi: 'REGISTRO EXISTOSO',
  nowEnterPass: 'Ahora puedes ingresar con tu password',
  unRegisteredUser: 'USUARIO NO REGISTRADO',
  checkRut: 'Verifique su número de RUT y vuelva a intentarlo',
  accept: 'Aceptar',
  used: 'Usada',
  new: 'Nueva',
  registrationForm: 'FORMULARIO DE REGISTRO',
  vin: 'VIN',
  enterVin: 'Ingresa el VIN de tu moto',
  regiForm: 'FORMULARIO REGISTRO',
  name: 'Nombre',
  enterName: 'Ingresa tu nombre',
  surname: 'Apellidos',
  enterLastName: 'Ingresa tu apellido',
  birthDate: 'Fecha nacimiento',
  enterDOB: 'Ingresa tu fecha de nacimiento',
  email: 'Email',
  enterEmail: 'Ingresa tu correo electrónico',
  telephone: 'Teléfono',
  enterTelephone: 'Ingresa un número de contacto',
  contactDealer: 'COMUNICATE CON UN DISTRIBUIDOR',
  enterContactEmail: 'Ingresa un correo de contacto',
  selectADistributor: 'Selecciona un distribuidor',
  selectTheDistributor: 'Selecciona el distribuidor',
  newOrUsedMotorcycle: '¿MOTO NUEVA O USADA?',
  selectOption: 'Selecciona una opción:',
  successfulRegi: 'REGISTRO EXITOSO',
  submittedForm: 'FORMULARIO ENVIADO',
  dataSent: 'DATOS ENVIADOS',
  nowLoginWithPassword: 'Ahora puedes ingresar con tu contraseña',
  willContactYouShortly: 'Nos comunicaremos contigo a la brevedad',
  address: 'Dirección',
  commune: 'Comuna',
  region: 'Región',
  registeredVehicles: 'VEHÍCULOS REGISTRADOS',
  editProfile: 'Editar perfil',
  userProfile: 'PERFIL DE USUARIO',
  keep: 'Guardar',
  notifications: 'NOTIFICACIONES',
  eliminate: 'Eliminar',
  close: 'Cerrar',
  scheduleMaintance: 'Agendar mantención',
  downloadCertificare: 'Descargar certificado',
  return: 'Volver',
  selectLocation: 'Selecciona una ubicación',
  metropolitan: 'Metropolitana',
  city: 'Ciudad',
  santiago: 'Santiago',
  counts: 'Las Condes',
  searchResults: 'RESULTADOS DE BÚSQUEDA',
  myDocuments: 'Mis Documentos',
  createFolder: 'CREAR UNA CARPETA',
  docRequest: 'SOLICITUD DE DOCUMENTOS',
  selectTypeOfDoc: 'Selecciona el tipo de documento',
  send: 'Enviar',
  manuals: 'MANUALES',
  postSalesForm: 'FORMULARIO POST VENTA',
  selectReason: 'Selecciona una razón',
  whatReasonForQuery: '¿Cuál es la razón de tu consulta?',
  writeYourQuery: 'Escribe tu consulta',
  writeUsYourQuery: 'Escríbenos tu consulta',
  willSendYouEmailRespondingResponse:
    'Te enviaremos un correo respondiendo tu solicitud',
  specifyFolderName: 'Especifique el nombre de la carpeta',
  folderName: 'Nombre de la carpeta',
  create: 'Crear',
  cancel: 'Cancelar',
  createfolder: 'Crear carpeta',
  uploadFile: 'Subir archivo',
  lastMaintenance: 'Última mantención',
  attachTransferDoc: 'Adjuntar documento de transferencia',
  attachFile: 'Adjuntar archivo',
  enterAddress: 'Ingresa tu dirección',
  enterComuna: 'Ingresa tu comuna',
  enterRegion: 'Ingresa tu región',
  filedCantEmpty: 'Fältet får inte vara tomt',
  passDoNotMatch: 'De angivna lösenorden stämmer inte överens',
  passValidation:
    'The password must be at least 8 characters long. The password must contain at least one lowercase letter, one uppercase letter, one number and one special character.',
  selectRegion: 'Seleccione una región',
  selectCity: 'Selecciona una ciudad',
  maintenanceManual: 'Manual de mantenimiento',
  userManual: 'Manual de usuario',
  userManualDesc:
    'Instrucciones y guías para el uso adecuado de tu motocicleta',
  maintenanceManualDesc:
    'Indicaciones del fabricante para el mantenimiento de tu motocicleta',
  whatsappNotInstalled: 'WhatsApp no ​​está instalado en tu dispositivo',
  phoneNotValid: 'El número de teléfono no es válido',
  passNotMatch:
    'Oops! Passwords do not match. Please ensure both passwords match before proceeding',
};
