export const types = {
  STORE_AUTH_TOKEN: 'STORE_AUTH_TOKEN',
  LOAD_AUTH_TOKEN: 'LOAD_AUTH_TOKEN',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  REGISTER_REJECTED_REQUEST: 'REGISTER_REJECTED_REQUEST',
  REGISTER_REJECTED_SUCCESS: 'REGISTER_REJECTED_SUCCESS',
  REGISTER_REJECTED_FAILURE: 'REGISTER_REJECTED_FAILURE',

  FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  RECOVER_PASSWORD_REQUEST: 'RECOVER_PASSWORD_REQUEST',
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RECOVER_PASSWORD_FAILURE: 'RECOVER_PASSWORD_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  DEVICE_TOKEN_REQUEST: 'DEVICE_TOKEN_REQUEST',
  DEVICE_TOKEN_SUCCESS: 'DEVICE_TOKEN_SUCCESS',
  DEVICE_TOKEN_FAILURE: 'DEVICE_TOKEN_FAILURE',

  FETCH_DOCUMENTS_REQUEST: 'FETCH_DOCUMENTS_REQUEST',
  FETCH_DOCUMENTS_SUCCESS: 'FETCH_DOCUMENTS_SUCCESS',
  FETCH_DOCUMENTS_FAILURE: 'FETCH_DOCUMENTS_FAILURE',

  DOCUMENT_TYPES_REQUEST: 'DOCUMENT_TYPES_REQUEST',
  DOCUMENT_TYPES_SUCCESS: 'DOCUMENT_TYPES_SUCCESS',
  DOCUMENT_TYPES_FAILURE: 'DOCUMENT_TYPES_FAILURE',

  UPLOAD_DOCUMENT_REQUEST: 'UPLOAD_DOCUMENT_REQUEST',
  UPLOAD_DOCUMENT_SUCCESS: 'UPLOAD_DOCUMENT_SUCCESS',
  UPLOAD_DOCUMENT_FAILURE: 'UPLOAD_DOCUMENT_FAILURE',

  DELETE_DOCUMENT_REQUEST: 'DELETE_DOCUMENT_REQUEST',
  DELETE_DOCUMENT_SUCCESS: 'DELETE_DOCUMENT_SUCCESS',
  DELETE_DOCUMENT_FAILURE: 'DELETE_DOCUMENT_FAILURE',

  CREATE_FOLDER_REQUEST: 'CREATE_FOLDER_REQUEST',
  CREATE_FOLDER_SUCCESS: 'CREATE_FOLDER_SUCCESS',
  CREATE_FOLDER_FAILURE: 'CREATE_FOLDER_FAILURE',

  LOST_DOCUMENTS_REQUEST: 'LOST_DOCUMENTS_REQUEST',
  LOST_DOCUMENTS_SUCCESS: 'LOST_DOCUMENTS_SUCCESS',
  LOST_DOCUMENTS_FAILURE: 'LOST_DOCUMENTS_FAILURE',

  FETCH_DISTRIBUTOS_REQUEST: 'FETCH_DISTRIBUTOS_REQUEST',
  FETCH_DISTRIBUTOS_SUCCESS: 'FETCH_DISTRIBUTOS_SUCCESS',
  FETCH_DISTRIBUTOS_FAILURE: 'FETCH_DISTRIBUTOS_FAILURE',

  FETCH_MAINTENANCE_URLS_REQUEST: 'FETCH_MAINTENANCE_URLS_REQUEST',
  FETCH_MAINTENANCE_URLS_SUCCESS: 'FETCH_MAINTENANCE_URLS_SUCCESS',
  FETCH_MAINTENANCE_URLS_DELETE: 'FETCH_MAINTENANCE_URLS_DELETE',
};
